[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
markers = [
#     "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "devel: marks tests as development tests",
]
pythonpath = [
  "."
]
